### ISSUE TITLE
AttributionError: 'module' object has no attribute 'mul'

### ISSUE THREAD

**Issue by sajeelk** [llSourcell/Game-AI#10]
[2017-04-13 14:47:10,786] Making new env: SpaceInvaders-v0
Traceback (most recent call last):
  File "Game-AI/atari.py", line 64, in <module>
    agent = DQN(env, args)
  File "/Users/MacMiniUser/Documents/ai/sentdex/Game-AI/dqn.py", line 48, in __init__
    self.q_train = tf.reduce_max(tf.mul(self.train_net.y, self.actions), reduction_indices=1)
AttributeError: 'module' object has no attribute 'mul'

**Comment by joe3d1998** [comment]
use tf.multiply
